version: 2

before:
  hooks:
    - make web

builds:
  - id: kith-pms
    main: ./cmd
    binary: kith-pms
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: kith-pms
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    formats:
      - tar.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

dockers_v2:
  - id: kith-pms-slim
    ids:
      - kith-pms
    dockerfile: Dockerfile.goreleaser-debian-slim
    images:
      - "ghcr.io/nhymxu/kith-pms"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"

  - id: kith-pms-distroless
    ids:
      - kith-pms
    dockerfile: Dockerfile.goreleaser
    images:
      - "ghcr.io/nhymxu/kith-pms"
    tags:
      - "{{ .Version }}-distroless"
      - "latest-distroless"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"

changelog:
  disable: true
