version: 2

before:
  hooks:
    - make web

builds:
  - id: kith-pms
    main: ./cmd
    binary: kith-pms
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: kith-pms
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    formats:
      - tar.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

dockers:
  - use: buildx
    ids:
      - kith-pms
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/nhymxu/kith-pms:{{ .Version }}-amd64"
      - "ghcr.io/nhymxu/kith-pms:latest-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - use: buildx
    ids:
      - kith-pms
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/nhymxu/kith-pms:{{ .Version }}-arm64"
      - "ghcr.io/nhymxu/kith-pms:latest-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - use: buildx
    ids:
      - kith-pms
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser-debian-slim
    image_templates:
      - "ghcr.io/nhymxu/kith-pms:{{ .Version }}-slim-amd64"
      - "ghcr.io/nhymxu/kith-pms:latest-slim-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - use: buildx
    ids:
      - kith-pms
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser-debian-slim
    image_templates:
      - "ghcr.io/nhymxu/kith-pms:{{ .Version }}-slim-arm64"
      - "ghcr.io/nhymxu/kith-pms:latest-slim-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/nhymxu/kith-pms:{{ .Version }}"
    image_templates:
      - "ghcr.io/nhymxu/kith-pms:{{ .Version }}-amd64"
      - "ghcr.io/nhymxu/kith-pms:{{ .Version }}-arm64"
  - name_template: "ghcr.io/nhymxu/kith-pms:latest"
    image_templates:
      - "ghcr.io/nhymxu/kith-pms:latest-amd64"
      - "ghcr.io/nhymxu/kith-pms:latest-arm64"
  - name_template: "ghcr.io/nhymxu/kith-pms:{{ .Version }}-slim"
    image_templates:
      - "ghcr.io/nhymxu/kith-pms:{{ .Version }}-slim-amd64"
      - "ghcr.io/nhymxu/kith-pms:{{ .Version }}-slim-arm64"
  - name_template: "ghcr.io/nhymxu/kith-pms:latest-slim"
    image_templates:
      - "ghcr.io/nhymxu/kith-pms:latest-slim-amd64"
      - "ghcr.io/nhymxu/kith-pms:latest-slim-arm64"

changelog:
  disable: true
