/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedRemindersIndexRouteImport } from './routes/_authed/reminders/index'
import { Route as AuthedPeopleIndexRouteImport } from './routes/_authed/people/index'
import { Route as AuthedNetworkIndexRouteImport } from './routes/_authed/network/index'
import { Route as AuthedMeIndexRouteImport } from './routes/_authed/me/index'
import { Route as AuthedJournalIndexRouteImport } from './routes/_authed/journal/index'
import { Route as AuthedImportantDatesIndexRouteImport } from './routes/_authed/important-dates/index'
import { Route as AuthedGiftsIndexRouteImport } from './routes/_authed/gifts/index'
import { Route as AuthedAuditIndexRouteImport } from './routes/_authed/audit/index'
import { Route as AuthedSettingsLayoutRouteImport } from './routes/_authed/settings/_layout'
import { Route as AuthedRemindersNewRouteImport } from './routes/_authed/reminders/new'
import { Route as AuthedRemindersReminderIdRouteImport } from './routes/_authed/reminders/$reminderId'
import { Route as AuthedPeopleNewRouteImport } from './routes/_authed/people/new'
import { Route as AuthedPeoplePersonIdRouteImport } from './routes/_authed/people/$personId'
import { Route as AuthedMeSetupRouteImport } from './routes/_authed/me/setup'
import { Route as AuthedJournalNewRouteImport } from './routes/_authed/journal/new'
import { Route as AuthedGiftsNewRouteImport } from './routes/_authed/gifts/new'
import { Route as AuthedJournalEntryIdRouteRouteImport } from './routes/_authed/journal/$entryId/route'
import { Route as AuthedGiftsGiftIdRouteRouteImport } from './routes/_authed/gifts/$giftId/route'
import { Route as AuthedJournalEntryIdIndexRouteImport } from './routes/_authed/journal/$entryId/index'
import { Route as AuthedGiftsGiftIdIndexRouteImport } from './routes/_authed/gifts/$giftId/index'
import { Route as AuthedSettingsLayoutSecurityRouteImport } from './routes/_authed/settings/_layout.security'
import { Route as AuthedSettingsLayoutRelationshipTypesRouteImport } from './routes/_authed/settings/_layout.relationship-types'
import { Route as AuthedSettingsLayoutPeopleLabelsRouteImport } from './routes/_authed/settings/_layout.people-labels'
import { Route as AuthedSettingsLayoutLabelsRouteImport } from './routes/_authed/settings/_layout.labels'
import { Route as AuthedSettingsLayoutJournalLabelsRouteImport } from './routes/_authed/settings/_layout.journal-labels'
import { Route as AuthedSettingsLayoutGeneralRouteImport } from './routes/_authed/settings/_layout.general'
import { Route as AuthedRemindersReminderIdEditRouteImport } from './routes/_authed/reminders/$reminderId.edit'
import { Route as AuthedPeoplePersonIdEditRouteImport } from './routes/_authed/people/$personId.edit'
import { Route as AuthedJournalEntryIdEditRouteImport } from './routes/_authed/journal/$entryId/edit'
import { Route as AuthedGiftsGiftIdEditRouteImport } from './routes/_authed/gifts/$giftId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRemindersIndexRoute = AuthedRemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleIndexRoute = AuthedPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetworkIndexRoute = AuthedNetworkIndexRouteImport.update({
  id: '/network/',
  path: '/network/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeIndexRoute = AuthedMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJournalIndexRoute = AuthedJournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedImportantDatesIndexRoute =
  AuthedImportantDatesIndexRouteImport.update({
    id: '/important-dates/',
    path: '/important-dates/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGiftsIndexRoute = AuthedGiftsIndexRouteImport.update({
  id: '/gifts/',
  path: '/gifts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditIndexRoute = AuthedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsLayoutRoute = AuthedSettingsLayoutRouteImport.update({
  id: '/settings/_layout',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRemindersNewRoute = AuthedRemindersNewRouteImport.update({
  id: '/reminders/new',
  path: '/reminders/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRemindersReminderIdRoute =
  AuthedRemindersReminderIdRouteImport.update({
    id: '/reminders/$reminderId',
    path: '/reminders/$reminderId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPeopleNewRoute = AuthedPeopleNewRouteImport.update({
  id: '/people/new',
  path: '/people/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeoplePersonIdRoute = AuthedPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeSetupRoute = AuthedMeSetupRouteImport.update({
  id: '/me/setup',
  path: '/me/setup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJournalNewRoute = AuthedJournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGiftsNewRoute = AuthedGiftsNewRouteImport.update({
  id: '/gifts/new',
  path: '/gifts/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJournalEntryIdRouteRoute =
  AuthedJournalEntryIdRouteRouteImport.update({
    id: '/journal/$entryId',
    path: '/journal/$entryId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGiftsGiftIdRouteRoute = AuthedGiftsGiftIdRouteRouteImport.update({
  id: '/gifts/$giftId',
  path: '/gifts/$giftId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJournalEntryIdIndexRoute =
  AuthedJournalEntryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedJournalEntryIdRouteRoute,
  } as any)
const AuthedGiftsGiftIdIndexRoute = AuthedGiftsGiftIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedGiftsGiftIdRouteRoute,
} as any)
const AuthedSettingsLayoutSecurityRoute =
  AuthedSettingsLayoutSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthedSettingsLayoutRoute,
  } as any)
const AuthedSettingsLayoutRelationshipTypesRoute =
  AuthedSettingsLayoutRelationshipTypesRouteImport.update({
    id: '/relationship-types',
    path: '/relationship-types',
    getParentRoute: () => AuthedSettingsLayoutRoute,
  } as any)
const AuthedSettingsLayoutPeopleLabelsRoute =
  AuthedSettingsLayoutPeopleLabelsRouteImport.update({
    id: '/people-labels',
    path: '/people-labels',
    getParentRoute: () => AuthedSettingsLayoutRoute,
  } as any)
const AuthedSettingsLayoutLabelsRoute =
  AuthedSettingsLayoutLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => AuthedSettingsLayoutRoute,
  } as any)
const AuthedSettingsLayoutJournalLabelsRoute =
  AuthedSettingsLayoutJournalLabelsRouteImport.update({
    id: '/journal-labels',
    path: '/journal-labels',
    getParentRoute: () => AuthedSettingsLayoutRoute,
  } as any)
const AuthedSettingsLayoutGeneralRoute =
  AuthedSettingsLayoutGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthedSettingsLayoutRoute,
  } as any)
const AuthedRemindersReminderIdEditRoute =
  AuthedRemindersReminderIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedRemindersReminderIdRoute,
  } as any)
const AuthedPeoplePersonIdEditRoute =
  AuthedPeoplePersonIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedPeoplePersonIdRoute,
  } as any)
const AuthedJournalEntryIdEditRoute =
  AuthedJournalEntryIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedJournalEntryIdRouteRoute,
  } as any)
const AuthedGiftsGiftIdEditRoute = AuthedGiftsGiftIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthedGiftsGiftIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/gifts/$giftId': typeof AuthedGiftsGiftIdRouteRouteWithChildren
  '/journal/$entryId': typeof AuthedJournalEntryIdRouteRouteWithChildren
  '/gifts/new': typeof AuthedGiftsNewRoute
  '/journal/new': typeof AuthedJournalNewRoute
  '/me/setup': typeof AuthedMeSetupRoute
  '/people/$personId': typeof AuthedPeoplePersonIdRouteWithChildren
  '/people/new': typeof AuthedPeopleNewRoute
  '/reminders/$reminderId': typeof AuthedRemindersReminderIdRouteWithChildren
  '/reminders/new': typeof AuthedRemindersNewRoute
  '/settings': typeof AuthedSettingsLayoutRouteWithChildren
  '/audit/': typeof AuthedAuditIndexRoute
  '/gifts/': typeof AuthedGiftsIndexRoute
  '/important-dates/': typeof AuthedImportantDatesIndexRoute
  '/journal/': typeof AuthedJournalIndexRoute
  '/me/': typeof AuthedMeIndexRoute
  '/network/': typeof AuthedNetworkIndexRoute
  '/people/': typeof AuthedPeopleIndexRoute
  '/reminders/': typeof AuthedRemindersIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/gifts/$giftId/edit': typeof AuthedGiftsGiftIdEditRoute
  '/journal/$entryId/edit': typeof AuthedJournalEntryIdEditRoute
  '/people/$personId/edit': typeof AuthedPeoplePersonIdEditRoute
  '/reminders/$reminderId/edit': typeof AuthedRemindersReminderIdEditRoute
  '/settings/general': typeof AuthedSettingsLayoutGeneralRoute
  '/settings/journal-labels': typeof AuthedSettingsLayoutJournalLabelsRoute
  '/settings/labels': typeof AuthedSettingsLayoutLabelsRoute
  '/settings/people-labels': typeof AuthedSettingsLayoutPeopleLabelsRoute
  '/settings/relationship-types': typeof AuthedSettingsLayoutRelationshipTypesRoute
  '/settings/security': typeof AuthedSettingsLayoutSecurityRoute
  '/gifts/$giftId/': typeof AuthedGiftsGiftIdIndexRoute
  '/journal/$entryId/': typeof AuthedJournalEntryIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/gifts/new': typeof AuthedGiftsNewRoute
  '/journal/new': typeof AuthedJournalNewRoute
  '/me/setup': typeof AuthedMeSetupRoute
  '/people/$personId': typeof AuthedPeoplePersonIdRouteWithChildren
  '/people/new': typeof AuthedPeopleNewRoute
  '/reminders/$reminderId': typeof AuthedRemindersReminderIdRouteWithChildren
  '/reminders/new': typeof AuthedRemindersNewRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/audit': typeof AuthedAuditIndexRoute
  '/gifts': typeof AuthedGiftsIndexRoute
  '/important-dates': typeof AuthedImportantDatesIndexRoute
  '/journal': typeof AuthedJournalIndexRoute
  '/me': typeof AuthedMeIndexRoute
  '/network': typeof AuthedNetworkIndexRoute
  '/people': typeof AuthedPeopleIndexRoute
  '/reminders': typeof AuthedRemindersIndexRoute
  '/gifts/$giftId/edit': typeof AuthedGiftsGiftIdEditRoute
  '/journal/$entryId/edit': typeof AuthedJournalEntryIdEditRoute
  '/people/$personId/edit': typeof AuthedPeoplePersonIdEditRoute
  '/reminders/$reminderId/edit': typeof AuthedRemindersReminderIdEditRoute
  '/settings/general': typeof AuthedSettingsLayoutGeneralRoute
  '/settings/journal-labels': typeof AuthedSettingsLayoutJournalLabelsRoute
  '/settings/labels': typeof AuthedSettingsLayoutLabelsRoute
  '/settings/people-labels': typeof AuthedSettingsLayoutPeopleLabelsRoute
  '/settings/relationship-types': typeof AuthedSettingsLayoutRelationshipTypesRoute
  '/settings/security': typeof AuthedSettingsLayoutSecurityRoute
  '/gifts/$giftId': typeof AuthedGiftsGiftIdIndexRoute
  '/journal/$entryId': typeof AuthedJournalEntryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/gifts/$giftId': typeof AuthedGiftsGiftIdRouteRouteWithChildren
  '/_authed/journal/$entryId': typeof AuthedJournalEntryIdRouteRouteWithChildren
  '/_authed/gifts/new': typeof AuthedGiftsNewRoute
  '/_authed/journal/new': typeof AuthedJournalNewRoute
  '/_authed/me/setup': typeof AuthedMeSetupRoute
  '/_authed/people/$personId': typeof AuthedPeoplePersonIdRouteWithChildren
  '/_authed/people/new': typeof AuthedPeopleNewRoute
  '/_authed/reminders/$reminderId': typeof AuthedRemindersReminderIdRouteWithChildren
  '/_authed/reminders/new': typeof AuthedRemindersNewRoute
  '/_authed/settings/_layout': typeof AuthedSettingsLayoutRouteWithChildren
  '/_authed/audit/': typeof AuthedAuditIndexRoute
  '/_authed/gifts/': typeof AuthedGiftsIndexRoute
  '/_authed/important-dates/': typeof AuthedImportantDatesIndexRoute
  '/_authed/journal/': typeof AuthedJournalIndexRoute
  '/_authed/me/': typeof AuthedMeIndexRoute
  '/_authed/network/': typeof AuthedNetworkIndexRoute
  '/_authed/people/': typeof AuthedPeopleIndexRoute
  '/_authed/reminders/': typeof AuthedRemindersIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/gifts/$giftId/edit': typeof AuthedGiftsGiftIdEditRoute
  '/_authed/journal/$entryId/edit': typeof AuthedJournalEntryIdEditRoute
  '/_authed/people/$personId/edit': typeof AuthedPeoplePersonIdEditRoute
  '/_authed/reminders/$reminderId/edit': typeof AuthedRemindersReminderIdEditRoute
  '/_authed/settings/_layout/general': typeof AuthedSettingsLayoutGeneralRoute
  '/_authed/settings/_layout/journal-labels': typeof AuthedSettingsLayoutJournalLabelsRoute
  '/_authed/settings/_layout/labels': typeof AuthedSettingsLayoutLabelsRoute
  '/_authed/settings/_layout/people-labels': typeof AuthedSettingsLayoutPeopleLabelsRoute
  '/_authed/settings/_layout/relationship-types': typeof AuthedSettingsLayoutRelationshipTypesRoute
  '/_authed/settings/_layout/security': typeof AuthedSettingsLayoutSecurityRoute
  '/_authed/gifts/$giftId/': typeof AuthedGiftsGiftIdIndexRoute
  '/_authed/journal/$entryId/': typeof AuthedJournalEntryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/gifts/$giftId'
    | '/journal/$entryId'
    | '/gifts/new'
    | '/journal/new'
    | '/me/setup'
    | '/people/$personId'
    | '/people/new'
    | '/reminders/$reminderId'
    | '/reminders/new'
    | '/settings'
    | '/audit/'
    | '/gifts/'
    | '/important-dates/'
    | '/journal/'
    | '/me/'
    | '/network/'
    | '/people/'
    | '/reminders/'
    | '/settings/'
    | '/gifts/$giftId/edit'
    | '/journal/$entryId/edit'
    | '/people/$personId/edit'
    | '/reminders/$reminderId/edit'
    | '/settings/general'
    | '/settings/journal-labels'
    | '/settings/labels'
    | '/settings/people-labels'
    | '/settings/relationship-types'
    | '/settings/security'
    | '/gifts/$giftId/'
    | '/journal/$entryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/gifts/new'
    | '/journal/new'
    | '/me/setup'
    | '/people/$personId'
    | '/people/new'
    | '/reminders/$reminderId'
    | '/reminders/new'
    | '/settings'
    | '/audit'
    | '/gifts'
    | '/important-dates'
    | '/journal'
    | '/me'
    | '/network'
    | '/people'
    | '/reminders'
    | '/gifts/$giftId/edit'
    | '/journal/$entryId/edit'
    | '/people/$personId/edit'
    | '/reminders/$reminderId/edit'
    | '/settings/general'
    | '/settings/journal-labels'
    | '/settings/labels'
    | '/settings/people-labels'
    | '/settings/relationship-types'
    | '/settings/security'
    | '/gifts/$giftId'
    | '/journal/$entryId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/gifts/$giftId'
    | '/_authed/journal/$entryId'
    | '/_authed/gifts/new'
    | '/_authed/journal/new'
    | '/_authed/me/setup'
    | '/_authed/people/$personId'
    | '/_authed/people/new'
    | '/_authed/reminders/$reminderId'
    | '/_authed/reminders/new'
    | '/_authed/settings/_layout'
    | '/_authed/audit/'
    | '/_authed/gifts/'
    | '/_authed/important-dates/'
    | '/_authed/journal/'
    | '/_authed/me/'
    | '/_authed/network/'
    | '/_authed/people/'
    | '/_authed/reminders/'
    | '/_authed/settings/'
    | '/_authed/gifts/$giftId/edit'
    | '/_authed/journal/$entryId/edit'
    | '/_authed/people/$personId/edit'
    | '/_authed/reminders/$reminderId/edit'
    | '/_authed/settings/_layout/general'
    | '/_authed/settings/_layout/journal-labels'
    | '/_authed/settings/_layout/labels'
    | '/_authed/settings/_layout/people-labels'
    | '/_authed/settings/_layout/relationship-types'
    | '/_authed/settings/_layout/security'
    | '/_authed/gifts/$giftId/'
    | '/_authed/journal/$entryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reminders/': {
      id: '/_authed/reminders/'
      path: '/reminders'
      fullPath: '/reminders/'
      preLoaderRoute: typeof AuthedRemindersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people/': {
      id: '/_authed/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthedPeopleIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/network/': {
      id: '/_authed/network/'
      path: '/network'
      fullPath: '/network/'
      preLoaderRoute: typeof AuthedNetworkIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/': {
      id: '/_authed/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthedMeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/journal/': {
      id: '/_authed/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof AuthedJournalIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/important-dates/': {
      id: '/_authed/important-dates/'
      path: '/important-dates'
      fullPath: '/important-dates/'
      preLoaderRoute: typeof AuthedImportantDatesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/gifts/': {
      id: '/_authed/gifts/'
      path: '/gifts'
      fullPath: '/gifts/'
      preLoaderRoute: typeof AuthedGiftsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit/': {
      id: '/_authed/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthedAuditIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/_layout': {
      id: '/_authed/settings/_layout'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reminders/new': {
      id: '/_authed/reminders/new'
      path: '/reminders/new'
      fullPath: '/reminders/new'
      preLoaderRoute: typeof AuthedRemindersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reminders/$reminderId': {
      id: '/_authed/reminders/$reminderId'
      path: '/reminders/$reminderId'
      fullPath: '/reminders/$reminderId'
      preLoaderRoute: typeof AuthedRemindersReminderIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people/new': {
      id: '/_authed/people/new'
      path: '/people/new'
      fullPath: '/people/new'
      preLoaderRoute: typeof AuthedPeopleNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people/$personId': {
      id: '/_authed/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthedPeoplePersonIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me/setup': {
      id: '/_authed/me/setup'
      path: '/me/setup'
      fullPath: '/me/setup'
      preLoaderRoute: typeof AuthedMeSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/journal/new': {
      id: '/_authed/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof AuthedJournalNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/gifts/new': {
      id: '/_authed/gifts/new'
      path: '/gifts/new'
      fullPath: '/gifts/new'
      preLoaderRoute: typeof AuthedGiftsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/journal/$entryId': {
      id: '/_authed/journal/$entryId'
      path: '/journal/$entryId'
      fullPath: '/journal/$entryId'
      preLoaderRoute: typeof AuthedJournalEntryIdRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/gifts/$giftId': {
      id: '/_authed/gifts/$giftId'
      path: '/gifts/$giftId'
      fullPath: '/gifts/$giftId'
      preLoaderRoute: typeof AuthedGiftsGiftIdRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/journal/$entryId/': {
      id: '/_authed/journal/$entryId/'
      path: '/'
      fullPath: '/journal/$entryId/'
      preLoaderRoute: typeof AuthedJournalEntryIdIndexRouteImport
      parentRoute: typeof AuthedJournalEntryIdRouteRoute
    }
    '/_authed/gifts/$giftId/': {
      id: '/_authed/gifts/$giftId/'
      path: '/'
      fullPath: '/gifts/$giftId/'
      preLoaderRoute: typeof AuthedGiftsGiftIdIndexRouteImport
      parentRoute: typeof AuthedGiftsGiftIdRouteRoute
    }
    '/_authed/settings/_layout/security': {
      id: '/_authed/settings/_layout/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsLayoutSecurityRouteImport
      parentRoute: typeof AuthedSettingsLayoutRoute
    }
    '/_authed/settings/_layout/relationship-types': {
      id: '/_authed/settings/_layout/relationship-types'
      path: '/relationship-types'
      fullPath: '/settings/relationship-types'
      preLoaderRoute: typeof AuthedSettingsLayoutRelationshipTypesRouteImport
      parentRoute: typeof AuthedSettingsLayoutRoute
    }
    '/_authed/settings/_layout/people-labels': {
      id: '/_authed/settings/_layout/people-labels'
      path: '/people-labels'
      fullPath: '/settings/people-labels'
      preLoaderRoute: typeof AuthedSettingsLayoutPeopleLabelsRouteImport
      parentRoute: typeof AuthedSettingsLayoutRoute
    }
    '/_authed/settings/_layout/labels': {
      id: '/_authed/settings/_layout/labels'
      path: '/labels'
      fullPath: '/settings/labels'
      preLoaderRoute: typeof AuthedSettingsLayoutLabelsRouteImport
      parentRoute: typeof AuthedSettingsLayoutRoute
    }
    '/_authed/settings/_layout/journal-labels': {
      id: '/_authed/settings/_layout/journal-labels'
      path: '/journal-labels'
      fullPath: '/settings/journal-labels'
      preLoaderRoute: typeof AuthedSettingsLayoutJournalLabelsRouteImport
      parentRoute: typeof AuthedSettingsLayoutRoute
    }
    '/_authed/settings/_layout/general': {
      id: '/_authed/settings/_layout/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthedSettingsLayoutGeneralRouteImport
      parentRoute: typeof AuthedSettingsLayoutRoute
    }
    '/_authed/reminders/$reminderId/edit': {
      id: '/_authed/reminders/$reminderId/edit'
      path: '/edit'
      fullPath: '/reminders/$reminderId/edit'
      preLoaderRoute: typeof AuthedRemindersReminderIdEditRouteImport
      parentRoute: typeof AuthedRemindersReminderIdRoute
    }
    '/_authed/people/$personId/edit': {
      id: '/_authed/people/$personId/edit'
      path: '/edit'
      fullPath: '/people/$personId/edit'
      preLoaderRoute: typeof AuthedPeoplePersonIdEditRouteImport
      parentRoute: typeof AuthedPeoplePersonIdRoute
    }
    '/_authed/journal/$entryId/edit': {
      id: '/_authed/journal/$entryId/edit'
      path: '/edit'
      fullPath: '/journal/$entryId/edit'
      preLoaderRoute: typeof AuthedJournalEntryIdEditRouteImport
      parentRoute: typeof AuthedJournalEntryIdRouteRoute
    }
    '/_authed/gifts/$giftId/edit': {
      id: '/_authed/gifts/$giftId/edit'
      path: '/edit'
      fullPath: '/gifts/$giftId/edit'
      preLoaderRoute: typeof AuthedGiftsGiftIdEditRouteImport
      parentRoute: typeof AuthedGiftsGiftIdRouteRoute
    }
  }
}

interface AuthedGiftsGiftIdRouteRouteChildren {
  AuthedGiftsGiftIdEditRoute: typeof AuthedGiftsGiftIdEditRoute
  AuthedGiftsGiftIdIndexRoute: typeof AuthedGiftsGiftIdIndexRoute
}

const AuthedGiftsGiftIdRouteRouteChildren: AuthedGiftsGiftIdRouteRouteChildren =
  {
    AuthedGiftsGiftIdEditRoute: AuthedGiftsGiftIdEditRoute,
    AuthedGiftsGiftIdIndexRoute: AuthedGiftsGiftIdIndexRoute,
  }

const AuthedGiftsGiftIdRouteRouteWithChildren =
  AuthedGiftsGiftIdRouteRoute._addFileChildren(
    AuthedGiftsGiftIdRouteRouteChildren,
  )

interface AuthedJournalEntryIdRouteRouteChildren {
  AuthedJournalEntryIdEditRoute: typeof AuthedJournalEntryIdEditRoute
  AuthedJournalEntryIdIndexRoute: typeof AuthedJournalEntryIdIndexRoute
}

const AuthedJournalEntryIdRouteRouteChildren: AuthedJournalEntryIdRouteRouteChildren =
  {
    AuthedJournalEntryIdEditRoute: AuthedJournalEntryIdEditRoute,
    AuthedJournalEntryIdIndexRoute: AuthedJournalEntryIdIndexRoute,
  }

const AuthedJournalEntryIdRouteRouteWithChildren =
  AuthedJournalEntryIdRouteRoute._addFileChildren(
    AuthedJournalEntryIdRouteRouteChildren,
  )

interface AuthedPeoplePersonIdRouteChildren {
  AuthedPeoplePersonIdEditRoute: typeof AuthedPeoplePersonIdEditRoute
}

const AuthedPeoplePersonIdRouteChildren: AuthedPeoplePersonIdRouteChildren = {
  AuthedPeoplePersonIdEditRoute: AuthedPeoplePersonIdEditRoute,
}

const AuthedPeoplePersonIdRouteWithChildren =
  AuthedPeoplePersonIdRoute._addFileChildren(AuthedPeoplePersonIdRouteChildren)

interface AuthedRemindersReminderIdRouteChildren {
  AuthedRemindersReminderIdEditRoute: typeof AuthedRemindersReminderIdEditRoute
}

const AuthedRemindersReminderIdRouteChildren: AuthedRemindersReminderIdRouteChildren =
  {
    AuthedRemindersReminderIdEditRoute: AuthedRemindersReminderIdEditRoute,
  }

const AuthedRemindersReminderIdRouteWithChildren =
  AuthedRemindersReminderIdRoute._addFileChildren(
    AuthedRemindersReminderIdRouteChildren,
  )

interface AuthedSettingsLayoutRouteChildren {
  AuthedSettingsLayoutGeneralRoute: typeof AuthedSettingsLayoutGeneralRoute
  AuthedSettingsLayoutJournalLabelsRoute: typeof AuthedSettingsLayoutJournalLabelsRoute
  AuthedSettingsLayoutLabelsRoute: typeof AuthedSettingsLayoutLabelsRoute
  AuthedSettingsLayoutPeopleLabelsRoute: typeof AuthedSettingsLayoutPeopleLabelsRoute
  AuthedSettingsLayoutRelationshipTypesRoute: typeof AuthedSettingsLayoutRelationshipTypesRoute
  AuthedSettingsLayoutSecurityRoute: typeof AuthedSettingsLayoutSecurityRoute
}

const AuthedSettingsLayoutRouteChildren: AuthedSettingsLayoutRouteChildren = {
  AuthedSettingsLayoutGeneralRoute: AuthedSettingsLayoutGeneralRoute,
  AuthedSettingsLayoutJournalLabelsRoute:
    AuthedSettingsLayoutJournalLabelsRoute,
  AuthedSettingsLayoutLabelsRoute: AuthedSettingsLayoutLabelsRoute,
  AuthedSettingsLayoutPeopleLabelsRoute: AuthedSettingsLayoutPeopleLabelsRoute,
  AuthedSettingsLayoutRelationshipTypesRoute:
    AuthedSettingsLayoutRelationshipTypesRoute,
  AuthedSettingsLayoutSecurityRoute: AuthedSettingsLayoutSecurityRoute,
}

const AuthedSettingsLayoutRouteWithChildren =
  AuthedSettingsLayoutRoute._addFileChildren(AuthedSettingsLayoutRouteChildren)

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedGiftsGiftIdRouteRoute: typeof AuthedGiftsGiftIdRouteRouteWithChildren
  AuthedJournalEntryIdRouteRoute: typeof AuthedJournalEntryIdRouteRouteWithChildren
  AuthedGiftsNewRoute: typeof AuthedGiftsNewRoute
  AuthedJournalNewRoute: typeof AuthedJournalNewRoute
  AuthedMeSetupRoute: typeof AuthedMeSetupRoute
  AuthedPeoplePersonIdRoute: typeof AuthedPeoplePersonIdRouteWithChildren
  AuthedPeopleNewRoute: typeof AuthedPeopleNewRoute
  AuthedRemindersReminderIdRoute: typeof AuthedRemindersReminderIdRouteWithChildren
  AuthedRemindersNewRoute: typeof AuthedRemindersNewRoute
  AuthedSettingsLayoutRoute: typeof AuthedSettingsLayoutRouteWithChildren
  AuthedAuditIndexRoute: typeof AuthedAuditIndexRoute
  AuthedGiftsIndexRoute: typeof AuthedGiftsIndexRoute
  AuthedImportantDatesIndexRoute: typeof AuthedImportantDatesIndexRoute
  AuthedJournalIndexRoute: typeof AuthedJournalIndexRoute
  AuthedMeIndexRoute: typeof AuthedMeIndexRoute
  AuthedNetworkIndexRoute: typeof AuthedNetworkIndexRoute
  AuthedPeopleIndexRoute: typeof AuthedPeopleIndexRoute
  AuthedRemindersIndexRoute: typeof AuthedRemindersIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedGiftsGiftIdRouteRoute: AuthedGiftsGiftIdRouteRouteWithChildren,
  AuthedJournalEntryIdRouteRoute: AuthedJournalEntryIdRouteRouteWithChildren,
  AuthedGiftsNewRoute: AuthedGiftsNewRoute,
  AuthedJournalNewRoute: AuthedJournalNewRoute,
  AuthedMeSetupRoute: AuthedMeSetupRoute,
  AuthedPeoplePersonIdRoute: AuthedPeoplePersonIdRouteWithChildren,
  AuthedPeopleNewRoute: AuthedPeopleNewRoute,
  AuthedRemindersReminderIdRoute: AuthedRemindersReminderIdRouteWithChildren,
  AuthedRemindersNewRoute: AuthedRemindersNewRoute,
  AuthedSettingsLayoutRoute: AuthedSettingsLayoutRouteWithChildren,
  AuthedAuditIndexRoute: AuthedAuditIndexRoute,
  AuthedGiftsIndexRoute: AuthedGiftsIndexRoute,
  AuthedImportantDatesIndexRoute: AuthedImportantDatesIndexRoute,
  AuthedJournalIndexRoute: AuthedJournalIndexRoute,
  AuthedMeIndexRoute: AuthedMeIndexRoute,
  AuthedNetworkIndexRoute: AuthedNetworkIndexRoute,
  AuthedPeopleIndexRoute: AuthedPeopleIndexRoute,
  AuthedRemindersIndexRoute: AuthedRemindersIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
