// Package templates contains templ component definitions.
// The actual component implementations are generated by `templ generate`
// into *_templ.go files (gitignored). This stub file ensures the package
// compiles and exports the correct function signatures before codegen runs,
// satisfying `go vet` and IDE tooling.
//
// Run `make templ` (or `make assets`) to regenerate.
//
// NOTE: when *_templ.go files are present after `make templ`, the generated
// files will re-declare these symbols and this stub must be removed or the
// build tags adjusted. The stub is removed automatically by templ generate.
// For now it provides the minimal surface area for go vet to pass.
package templates

import (
	"context"
	"io"
	"time"

	"github.com/a-h/templ"
	"github.com/nhymxu/kith-pms/internal/journal"
	"github.com/nhymxu/kith-pms/internal/labels"
	"github.com/nhymxu/kith-pms/internal/people"
)

// componentFunc is a thin templ.Component adapter around a render function.
type componentFunc func(ctx context.Context, w io.Writer) error

func (f componentFunc) Render(ctx context.Context, w io.Writer) error {
	return f(ctx, w)
}

func stub(msg string) templ.Component {
	return componentFunc(func(_ context.Context, w io.Writer) error {
		_, err := io.WriteString(w, "<!-- "+msg+": run make templ -->")
		return err
	})
}

// ---- layout / shared --------------------------------------------------------

// Layout returns the base HTML layout component.
func Layout(title string) templ.Component {
	_ = title
	return stub("layout stub")
}

// DashboardData holds all data needed to render the dashboard homepage.
type DashboardData struct {
	PeopleCount     int
	LabelsCount     int
	ActivitiesCount int
	RecentActivities []journal.Activity
	RecentPeople     []people.Person
}

// Home renders the dashboard homepage component.
func Home(data DashboardData) templ.Component {
	_ = data
	return stub("home/dashboard stub")
}

// Error404 renders the 404 Not Found page.
func Error404() templ.Component {
	return stub("error_404 stub")
}

// Error500 renders the 500 Internal Server Error page.
func Error500(msg string) templ.Component {
	_ = msg
	return stub("error_500 stub")
}

// Login returns the login page component.
func Login(csrfToken, next string, showError bool) templ.Component {
	_, _, _ = csrfToken, next, showError
	return stub("login stub")
}

// ---- people -----------------------------------------------------------------

// PeopleListParams holds data for the people list page.
type PeopleListParams struct {
	People       []people.Person
	Query        string
	Page         int
	HasMore      bool
	AllLabels    []labels.Label
	ActiveLabels []int64
}

// PeopleFormParams holds data for the person create/edit form page.
type PeopleFormParams struct {
	Person    people.Person
	Contacts  []people.ContactInfo
	Locations []people.Location
	CSRFToken string
	IsEdit    bool
	Error     string
}

// PeopleList renders the /people index page.
func PeopleList(params PeopleListParams) templ.Component {
	_ = params
	return stub("people_list stub")
}

// PeopleForm renders the create or edit form for a person.
func PeopleForm(params PeopleFormParams) templ.Component {
	_ = params
	return stub("people_form stub")
}

// PeopleDetailParams holds data for the person detail page.
type PeopleDetailParams struct {
	Person           people.Person
	Labels           []labels.Label
	AllLabels        []labels.Label
	CSRFToken        string
	RecentActivities []journal.Activity // latest 10 activities (Phase 5)
}

// PeopleDetail renders the detail view for a single person.
func PeopleDetail(params PeopleDetailParams) templ.Component {
	_ = params
	return stub("people_detail stub")
}

// PeopleDeleteConfirm renders the inline delete confirmation snippet.
func PeopleDeleteConfirm(p people.Person, csrfToken string) templ.Component {
	_, _ = p, csrfToken
	return stub("people_delete_confirm stub")
}

// ContactRow renders a blank contact input row for htmx insertion.
func ContactRow(index int) templ.Component {
	_ = index
	return stub("contact_row stub")
}

// ContactRowFilled renders a pre-filled contact input row for the edit form.
func ContactRowFilled(index int, c people.ContactInfo) templ.Component {
	_, _ = index, c
	return stub("contact_row_filled stub")
}

// LocationRow renders a blank location input row for htmx insertion.
func LocationRow(index int) templ.Component {
	_ = index
	return stub("location_row stub")
}

// LocationRowFilled renders a pre-filled location input row for the edit form.
func LocationRowFilled(index int, l people.Location) templ.Component {
	_, _ = index, l
	return stub("location_row_filled stub")
}

// dobValue formats a nullable *time.Time as YYYY-MM-DD for <input type="date">.
// Declared here so handlers can call it; real implementation lives in people_form.templ.
func dobValue(t *time.Time) string {
	if t == nil {
		return ""
	}
	return t.Format("2006-01-02")
}

// ---- labels -----------------------------------------------------------------

// LabelsListParams holds data for the labels index page.
type LabelsListParams struct {
	Labels      []labels.Label
	CSRFToken   string
	CreateError string
	CreateName  string
	CreateColor string
}

// LabelEditParams holds data for the label edit page.
type LabelEditParams struct {
	Label     labels.Label
	CSRFToken string
	Error     string
}

// LabelsList renders the /labels index page.
func LabelsList(params LabelsListParams) templ.Component {
	_ = params
	return stub("labels_list stub")
}

// LabelEdit renders the edit form for a single label.
func LabelEdit(params LabelEditParams) templ.Component {
	_ = params
	return stub("label_edit stub")
}

// LabelChip renders a colored badge for a label.
func LabelChip(l labels.Label) templ.Component {
	_ = l
	return stub("label_chip stub")
}

// LabelChipDetach renders a label chip with a detach button.
func LabelChipDetach(l labels.Label, personID int64, csrfToken string) templ.Component {
	_, _, _ = l, personID, csrfToken
	return stub("label_chip_detach stub")
}

// PersonLabelsStrip renders the full chip strip for a person (htmx swap target).
func PersonLabelsStrip(attached []labels.Label, all []labels.Label, personID int64, csrfToken string) templ.Component {
	_, _, _, _ = attached, all, personID, csrfToken
	return stub("person_labels_strip stub")
}

// LabelDropdown renders an "Add label" select+button.
func LabelDropdown(available []labels.Label, personID int64, csrfToken string) templ.Component {
	_, _, _ = available, personID, csrfToken
	return stub("label_dropdown stub")
}

// ---- journal ----------------------------------------------------------------

// JournalListParams holds data for the journal index page.
type JournalListParams struct {
	Activities []journal.Activity
	Query      string
	FromDate   string
	ToDate     string
	Page       int
	HasMore    bool
}

// JournalFormParams holds data for the journal create/edit form.
type JournalFormParams struct {
	Activity  journal.Activity
	CSRFToken string
	IsEdit    bool
	Error     string
}

// JournalDetailParams holds data for the journal detail page.
type JournalDetailParams struct {
	Activity  journal.Activity
	CSRFToken string
}

// PersonSummary is a lightweight person record used in picker results.
type PersonSummary struct {
	ID   int64
	Name string
}

// JournalList renders the /journal index page.
func JournalList(params JournalListParams) templ.Component {
	_ = params
	return stub("journal_list stub")
}

// JournalForm renders the create or edit form for a journal entry.
func JournalForm(params JournalFormParams) templ.Component {
	_ = params
	return stub("journal_form stub")
}

// JournalDetail renders the detail view for a single journal entry.
func JournalDetail(params JournalDetailParams) templ.Component {
	_ = params
	return stub("journal_detail stub")
}

// JournalDeleteConfirm renders the inline delete confirmation snippet (htmx fragment).
func JournalDeleteConfirm(a journal.Activity, csrfToken string) templ.Component {
	_, _ = a, csrfToken
	return stub("journal_delete_confirm stub")
}

// JournalRow renders a single activity list item fragment.
func JournalRow(a journal.Activity) templ.Component {
	_ = a
	return stub("journal_row stub")
}

// PersonPickerResults renders an htmx dropdown of matching people.
func PersonPickerResults(ps []people.Person) templ.Component {
	_ = ps
	return stub("person_picker_results stub")
}

// PersonChip renders a selected-person chip with hidden input and remove button.
func PersonChip(personID int64, name string) templ.Component {
	_, _ = personID, name
	return stub("person_chip stub")
}
